### ISSUE TITLE
Missing "requirements.txt" in PyPI package

### ISSUE THREAD

**Issue by hmontenegro** [ktmeaton/NCBImeta#10]
**Describe the bug**
The PyPI package of NCBImeta is missing the "requirements.txt" file, causing installation to fail. I am using virtualenv.

**To Reproduce**
```
pip install NCBImeta
```
Results in:
```
Collecting NCBImeta
  Using cached NCBImeta-0.6.5.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/program2/bin/NCBImeta/0.6.5/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5gcxpj4l/NCBImeta/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5gcxpj4l/NCBImeta/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5gcxpj4l/NCBImeta/pip-egg-info
         cwd: /tmp/pip-install-5gcxpj4l/NCBImeta/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5gcxpj4l/NCBImeta/setup.py", line 6, in <module>
        with open("requirements.txt", 'r') as r:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**System (please complete the following information):**
 - OS: Debian 9
 - Python: 3.5.3
 - NCBImeta: 0.6.5

**Comment by hmontenegro** [comment]
Downloading source from Github and installing works:

```
curl -LOJR https://github.com/ktmeaton/NCBImeta/archive/v0.6.5.tar.gz
pip install NCBImeta-0.6.5.tar.gz
```
Results in:
```
Processing ./NCBImeta-0.6.5.tar.gz
Collecting biopython==1.74
  Downloading biopython-1.74-cp35-cp35m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 7.4 MB/s 
Collecting PyYAML==5.1.2
  Downloading PyYAML-5.1.2.tar.gz (265 kB)
     |████████████████████████████████| 265 kB 13.8 MB/s 
Collecting numpy==1.16.4
  Using cached numpy-1.16.4-cp35-cp35m-manylinux1_x86_64.whl (17.2 MB)
Collecting lxml==4.4.2
  Downloading lxml-4.4.2-cp35-cp35m-manylinux1_x86_64.whl (5.7 MB)
     |████████████████████████████████| 5.7 MB 17.6 MB/s 
Building wheels for collected packages: NCBImeta, PyYAML
  Building wheel for NCBImeta (setup.py) ... done
  Created wheel for NCBImeta: filename=NCBImeta-0.6.5-py3-none-any.whl size=41893 sha256=e9fb14d6122a00edca4315021640de7fceb0c002315422a9beee046b38b6f3d0
  Stored in directory: /home/program2/.cache/pip/wheels/e3/3a/56/22395d52ac94833cc5ac5a709e7145f9572478089daba84f29
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.1.2-cp35-cp35m-linux_x86_64.whl size=44102 sha256=26b8698484f51e33ac5b853a2ccfc560fdd07e0f9b1afcdcf23ee1bb45891c83
  Stored in directory: /home/program2/.cache/pip/wheels/d3/f0/aa/67d37d73f76cabc6c1409b382780fa98df0a8aa83449791474
Successfully built NCBImeta PyYAML
Installing collected packages: numpy, biopython, PyYAML, lxml, NCBImeta
Successfully installed NCBImeta-0.6.5 PyYAML-5.1.2 biopython-1.74 lxml-4.4.2 numpy-1.16.4
```

**Comment by ktmeaton** [comment]
Thank you for identifying and documenting this important bug! I'm glad one of the other installation methods worked for you, but this is definitely an issue I need to fix. My notes to self about the next steps:
- [ ] Implement a manifest template to include ```requirements.txt``` in PyPI packages. [Helpful thread](https://github.com/alvinwan/tex2py/issues/2).
- [ ] Implement automated deployment checks for PyPI installation.

**Comment by ktmeaton** [comment]
Just leaving an update, I've got the new MANIFEST file to hopefully fix the PyPI packaging issue. I'm just tidying up some other bugfixes and will hopefully get that new release soon!

**Comment by ktmeaton** [comment]
Installing from the PyPI repository should proceed smoothly now for versions >=0.6.6.

Thanks again for identifying this bug!
