### ISSUE TITLE
TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'

### ISSUE THREAD

**Issue by ktmeaton** [ktmeaton/NCBImeta#13]
**Describe the bug**

Starting with biopython==1.77, a TypeError is raised when trying to parse the ID_handle.
```
Traceback (most recent call last):
  File "/home/ktmeaton/miniconda3/envs/ncbimeta-dev/bin/NCBImeta.py", line 630, in <module>
    FORCE_PAUSE_SECONDS,
  File "/home/ktmeaton/miniconda3/envs/ncbimeta-dev/bin/NCBImeta.py", line 453, in UpdateDB
    temp_b.write(str.encode(line))
TypeError: descriptor 'encode' requires a 'str' object but received a 'bytes'
```

**To Reproduce**

1. Upgrade biopython to 1.77 (ex. change in requirements file).
2. Run example command: 

```bash
NCBImeta.py --flat --config example/config.yaml
```

**Expected behavior**
No TypeErrors should be raised.

**System (please complete the following information):**

* Ubuntu 20.04 (WSL2)
* Python 3.7.6
* NCBImeta v0.6.6

** Possible solutions:

- [x] Identify what change in biopython==1.77 is causing this (https://github.com/biopython/biopython/issues/334, https://github.com/biopython/biopython/issues/3206).
- [x] Restrict biopython module to >=1.74,<1.77.

**Comment by ktmeaton** [comment]
My current solution is to restrict biopython to not use version 1.77. I've also now version-controlled all user and dev dependencies. This will be available in release v0.7.0, but for now will be available on the dev branch:

```bash
git clone -b dev https://github.com/ktmeaton/NCBImeta.git
```
