### ISSUE TITLE
Runtime error when processing a new table

### ISSUE THREAD

**Issue by ktmeaton** [ktmeaton/NCBImeta#2]
**Describe the Bug**
The program raises an error and exits when it begins processing queries for a new table (ex. BioSample). 

**To Reproduce**
Run the program with the example config file:
```python3 src/NCBImeta.py --flat --config example/config.yaml ```

**Expected Behavior**
The program should seamlessly transition to processing queries for the next table. Runtime Errors should be caught, retried an appropriate number of times, and only exit if the error truly cannot be handled appropriately.

**Additional Context**

OS: Ubuntu 18.04
Python Version: 3.7
Python Install Method: miniconda
NCBImeta Version: v0.3.5 (dev - 906b10c)

_Traceback (most recent call last):
  File "src/NCBImeta.py", line 526, in <module>
    UpdateDB(table, OUTPUT_DIR, DATABASE, EMAIL, SEARCH_TERM, TABLE_COLUMNS, LOG_PATH, DB_DIR, API_KEY, FORCE_PAUSE_SECONDS)
  File "src/NCBImeta.py", line 237, in UpdateDB
    record = Entrez.read(handle)
  File "/home/username/.local/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 474, in read
    record = handler.read(handle)
  File "/home/username/.local/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 333, in read
    self.parser.ParseFile(handle)
  File "/tmp/build/80754af9/python_1544812943833/work/Modules/pyexpat.c", line 466, in EndElement
  File "/home/username/.local/lib/python3.7/site-packages/Bio/Entrez/Parser.py", line 659, in endErrorElementHandler
    raise RuntimeError(value)
RuntimeError: Search Backend failed: read request has timed out. peer: 130.14.22.46:7011_

**Suggested Fix**
Wrap the code ```record = Entrez.read(handle)``` in a while statement, with try and except statements for RuntimeErrors. Retry Entrex.max_tries (default=3) before exiting with a custom Error statement.

**Comment by ktmeaton** [comment]
Implemented suggested fix in 58829cc.

Issue closure pending additional user testing.
