### ISSUE TITLE
Extra content at the end of the document

### ISSUE THREAD

**Issue by ktmeaton** [ktmeaton/NCBImeta#26]
**Describe the bug**
Using the `ncbimeta-0.8.2` package from `conda`, the example fails with the following output:

```text
NCBImeta was run with the following options:
        Config File: test/test.yaml
        Output Directory: test
        User Database: test.sqlite
        Tables: ['Assembly', 'BioSample', 'BioProject', 'SRA', 'Nucleotide', 'Pubmed']
        Search Terms:
                {'Assembly': '(SAMN12991206[BioSample])'}
                {'BioProject': '(PRJNA269675[BioProject IDs and Accessions])'}
                {'BioSample': '(SAMN12991206[Accession])'}
                {'SRA': '(SAMN12991206[BioSample])'}
                {'Nucleotide': '(SAMN12991206[BioSample])'}
                {'Pubmed': '(26634751[uid])'}


Flat mode was requested, organizational directories will not be used.

Creating database: test/test.sqlite

Connected to database: test/test.sqlite

Creating/Updating the Assembly table using the following parameters:
        Database:               test.sqlite
        Search Term:            (SAMN12991206[BioSample])
        Output Directory:       test


ID: 5025191
Processing record: 1/1
Traceback (most recent call last):
  File "/home/XXXX/miniconda3/envs/ncbimeta/lib/python3.8/site-packages/ncbimeta/NCBImetaUtilities.py", line 169, in xml_search
    xml_root = etree.fromstring(xml_root_string[2:-1])
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 1, column 61

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXX/miniconda3/envs/ncbimeta/bin/NCBImeta", line 623, in <module>
    UpdateDB(
  File "/home/XXXX/miniconda3/envs/ncbimeta/bin/NCBImeta", line 511, in UpdateDB
    NCBImetaUtilities.xml_search(
  File "/home/XXXX/miniconda3/envs/ncbimeta/lib/python3.8/site-packages/ncbimeta/NCBImetaUtilities.py", line 217, in xml_search
    xml_search(result, search_list, next_tag, column_name, xml_dict)
  File "/home/XXXX/miniconda3/envs/ncbimeta/lib/python3.8/site-packages/ncbimeta/NCBImetaUtilities.py", line 217, in xml_search
    xml_search(result, search_list, next_tag, column_name, xml_dict)
  File "/home/XXXX/miniconda3/envs/ncbimeta/lib/python3.8/site-packages/ncbimeta/NCBImetaUtilities.py", line 175, in xml_search
    xml_root = etree.fromstring(xml_root_string[2:-1])
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 1, column 61
```

**To Reproduce**
```bash
NCBImeta --flat --config test/test.yaml
```

**System (please complete the following information):**

* OS: Ubuntu 20.04
* Python: 3.8
* NCBImeta: v0.8.2

**Additional context**
 - The example works fine with a local install `pip install .`

**Comment by ktmeaton** [comment]
I suspect this is related to changes in the [`lxml`](https://github.com/lxml/lxml/releases) package, which has had 3 new releases in the last 48 hours.

**Comment by ktmeaton** [comment]
I will check back in when `lxml=4.7.1` is packaged for conda.

**Comment by ktmeaton** [comment]
Configuration that works:

```bash
mamba env create -f environment.yaml
conda activate ncbimeta
pip install .
NCBImeta --flat --config test/test.yaml
```

**environment.yaml**
```yaml
name: ncbimeta
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>3.6,<3.10
  - pip
  - anaconda::make
  - anaconda::gcc_impl_linux-64
  - anaconda::gcc_linux-64
  - anaconda::gxx_linux-64
```

**Comment by ktmeaton** [comment]
Configuration that works (install from PyPI):

```bash
mamba env create -f environment.yaml
conda activate ncbimeta
NCBImeta --flat --config test/test.yaml
```

```yaml
name: ncbimeta_pypi
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>3.6,<3.10
  - pip
  - anaconda::make
  - anaconda::gcc_impl_linux-64
  - anaconda::gcc_linux-64
  - anaconda::gxx_linux-64
  - pip:
    - ncbimeta==0.8.2
```

**Comment by ktmeaton** [comment]
Configuration that **DOESN'T** work (install from conda):

```bash
mamba env create -f environment.yaml
conda activate ncbimeta_conda
NCBImeta --flat --config test/test.yaml
```

```yaml
name: ncbimeta_conda
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python>3.6,<3.10
  - pip
  - anaconda::make
  - anaconda::gcc_impl_linux-64
  - anaconda::gcc_linux-64
  - anaconda::gxx_linux-64
  - ncbimeta==0.8.2
```

**Comment by ktmeaton** [comment]
The major difference between these two is pypi (working) uses `python=3.9.7` while conda (failing) uses `python=3.8.12`.

**Comment by ktmeaton** [comment]
I think this once again might be related to biopython.

**Comment by ktmeaton** [comment]
Actually it might also be that the numpy versions are too restrictive.

**Comment by ktmeaton** [comment]
The [github action for the example workflow](https://github.com/ktmeaton/NCBImeta/actions/runs/1689449505) now gives a comprehensive overview of exactly which install methods (`source`, `pypi`,  `conda`) and `python` versions (3.7, 3.8, 3.9. 3.10) are currently working.

---

- `source` | `NCBImeta v0.8.3dev`:
  - [x] python 3.7
  - [x] python 3.8
  - [x] python 3.9
  - [x] python 3.10

- `pypi` | `NCBImeta v0.8.2`:
  - [x] python 3.7
  - [x] python 3.8
  - [x] python 3.9
  - [ ] ❌ python 3.10 | `ERROR: Could not build wheels for numpy`

- `conda`  | (TBD)
  - [ ] python 3.7
  - [ ] python 3.8
  - [ ] python 3.9
  - [ ] python 3.10

**Comment by ktmeaton** [comment]
I think I've narrowed down the problem to `lxml` specifically.

1. Create the 'default' environment. This is broken.

```bash
mamba create -c bioconda -c conda-forge -n ncbimeta ncbimeta
conda activate lxml
```

2. Remove  `lxml` from conda.

```bash
pip uninstall lxml
```

3. Reinstall `lxml` from `PyPi`. This is now fixed.
```bash
pip install lxml
```
