### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType")

### ISSUE THREAD

**Issue by ktmeaton** [ktmeaton/NCBImeta#7]
**Describe the Bug**
NCBImeta.py crashes with the following error message.

Connected to database: output/database/yersinia_pestis_db.sqlite
Traceback (most recent call last):
  File "/home/USER/miniconda3/envs/MYENV/bin/NCBImeta.py", line 458, in <module>
    UpdateDB(table, OUTPUT_DIR, DATABASE, EMAIL, SEARCH_TERM, TABLE_COLUMNS, LOG_PATH, DB_DIR, API_KEY, FORCE_PAUSE_SECONDS)
  File "/home/USER/miniconda3/envs/MYENV/bin/NCBImeta.py", line 204, in UpdateDB
    "\t" + "Output Directory: " + "\t" + output_dir + "\n\n", flush = True)
TypeError: can only concatenate str (not "NoneType") to str

**Additional Context**
This error was raised when several yaml config parameters were left blank (oddly enough, this occurred when email was accidentally left blank).

**YAML**
OUTPUT_DIR : output
EMAIL : 

**Suggested Fix**
This should not be happening. I implemented custom error-catching for the YAML input step, but clearly it's not working well enough. Next steps:
1. Figure out why implemented error catching is missing this.
2. Catch and warn against missing mandatory parameters (ex. Email).

**Comment by ktmeaton** [comment]
**Suggested Fix** implemented in v0.6.4
